canonical/seldon-core-operator

README.md

Updating the readme to create a cohesive branding for kubeflow charms
I moved the existing text to the $charm-instruction$ section. Let me know if you have any ideas on improving that section. 
The instruction section is also buried in the middle of the text. I think it's better to have a separate header for it.
The copy provided by Rob: https://docs.google.com/document/d/11FeczUu9Rk8PsgAayF6LIwUHA6RVKGwGY5bhxi5S6b4/edit

update readme with marketing copy

---

.github/workflows/ci.yaml
tests/integration/test_charm.py
tox.ini

* replaces kubectl call with lightkube
* splits tests into separate build_and_deploy and seldon_deployment (eg: job) tests for easier debugging of tests (this way if debugging the sample seldon job, the tests can run with `-k test_seldon_deployment` and wont rebuild/deploy the charm every time)
* runs everything in the test's juju model/namespace

suggested edits for the webhook label fixes

---

.github/workflows/ci.yaml

Change to be able to test training-operator 1.5.0 in microk8s 1.22
Merge after #30

ci: microk8s version bump 1.21->1.22

---

src/charm.py
tests/unit/test_operator.py

This PR standardizes handling the status when the unit is not leader and adds `leader-elected` to observed events.

Observe leader-elected

---

renovate.json

We want only to scan pip compile requirements*.in files during renovate run not requirements*.txt. This PR also tries to fix chicken and egg problem during pip compile by specifying explicit order of scans.

Don't scan requirements*.txt for renovate runs

---

lib/charms/observability_libs/v0/metrics_endpoint_discovery.py
src/charm.py
tests/unit/test_operator.py
tox.ini

The original implementation of endpoint discovery had drifted (on Juju2 and Juju3), and the required observer was not started.
Correct the library, and some error handling for data in the charm itself.

Fix endpoint discovery

---

.github/workflows/integrate.yaml

to be consistent in all of our repos, use `charmed-kubernetes/actions-operator@main` in `Setup operator environment`

fix: use charmed-kubernetes/actions-operator@main

---

src/templates/auth_manifests.yaml.j2

fix: add kubeflow seldon aggregation rules

---

src/charm.py

This adds `force` to all `lightkube.Client.apply()` calls to mitigate #147.
See #147

fix: use `force` for lightkube.Client.apply

---

src/charm.py

This adds `force` to all `lightkube.Client.apply()` calls to mitigate [this issue](https://github.com/canonical/seldon-core-operator/issues/147)
(cherry picked from commit 58a245b049ea907eb8b05a924e9de98aed2f5e1b)

cherry pick 'use `force` for lightkube.Client.apply' to track/1.15

---

.github/workflows/integrate.yaml
examples/mlflowserver-v2.yaml
examples/mlflowserver.yaml
examples/xgboost-v2.yaml
examples/xgboost.yaml
src/charm.py
tests/integration/test_charm.py

**NOTE:** *This PR description only contains information related to code changes and testing, if required. All detailed information about problem statement, design, implementation, technical discussions, etc. is tracked in corresponding Github issue indicated below. This will ensure that important information is reliably recorded and tracked and not scattered across PR(s).*
**Details**
Refer to the following Github issue for more information on feature/fix that this PR is related to:
https://github.com/canonical/seldon-core-operator/issues/133
- Added integration test for Seldon prepackages servers: xgboost v1 and v2, mlflowserver v1.
- Remove tests fails intermittently.

feat: Integration tests for set of Seldon rocks

---

get-images.sh

Each repository needs a way to produce a list of all container image that are managed by charm and by workload. In some cases it can be done by parsing resource and in some cases a static list is created, because programmatic extraction is not warranted.
- Script the produce list of images. The list is static. Only one container image is extracted from config.yaml.
NOTE: When container images are replaced with ROCKs this script might become obsolete.

feat: script to get all images refernce by charm

---

src/templates/configmap.yaml.j2
tests/assets/crs/huggingface.yaml
tests/integration/test_seldon_servers.py

Details are in https://github.com/canonical/seldon-core-operator/issues/133
- Updated configmap with reference to rock.
- Added test for huggingface server Seldon Deployment
- Implemented integration test.

feat: mlserver-huggingface rock integration

---

src/templates/configmap.yaml.j2
tests/assets/crs/mlflowserver.yaml
tests/integration/test_seldon_servers.py

Details are in https://github.com/canonical/seldon-core-operator/issues/133
mlsrerver-sklearn rock required some adjustments in integration tests: changes to request and respose test data.
- Updated config map with reference to published rock.
- Updated integration tests.

feat: mlserver-sklearn integration

---

src/templates/configmap.yaml.j2
tests/integration/test_seldon_servers.py

Details are in https://github.com/canonical/seldon-core-operator/issues/133
- Added reference to published mlserver-xgboost rock to configmap.
- Update integration test response data.

feat: integration of mlserver-xgboost rock

---

tools/get-images-1.7-stable.sh

Repository specific list of images. Mostly static in this case.
Used by CVE scanning workflows and can be used to collect images URL for airgapped setup.
- Script that produces list of all workload managed container images that are related to this charm's workload.

feat: 1.7/stable list of images for this repo

---

.github/workflows/integrate.yaml
tox.ini

This PR includes the following changes:
* ci: increase storage of GH runners for integration testing
Increasing the storage of the GH runners will avoid potential issues when running integration
tests that deploy SeldonDeployments that require a significant amount of them.
Part of #185
* ci: run integration tests in different machines to avoid deploying seldon twice
Building and deploying seldon twice in a row may lead to errors while executing test cases from two different
test files. This change ensures each individual test file runs on its own environment.
Part of #185
* Integration tests may fail during the charm build stage because we are missing changes introduced by #184. To make sure that other CI runs without failures, this PR should be merged first.

ci: increase storage in GH runners and run integration tests in different machines

---

tests/integration/test_seldon_servers.py

Using a "remove" fixture we can guarantee that the SeldonDeployment under test is actually removed from the testing environment before proceeding with the test execution. This change prevents potential conflicts when the SeldonDeployment has the same name as a previously deployed one and keeps the testing environment clean before continuing.
This commit also moves some of the environment preparations to pytest fixtures to keep the test cases tidy and the test file reusable.
Part of #189

tests: remove SeldonDeployments even if the test case fails

---

tests/integration/utils.py

Increasing the retries and starting time of tenacity retries will ensure the SeldonDeployments can be active and ready to be tested in environments with resources limitations.
Part of #189

tests: increase number of retries and increase starting time for tenacity retries

---

src/charm.py

For some of the images, the charm attempts to separate the image name from the tag, splitting the string in two using `:` as a separator. However, this breaks the installation if the image name contains that special character, which could be the case if a local container registry address is provided for instance (e.g. `172.17.0.2:5000/tensorflow/serving:2.1.0`).
Use `rsplit` to ensure that the rightmost part of the string (following the last `:`) is parsed as the tag.
Closes #205

fix: Parse custom images with ":" in their name

---

tests/integration/test_charm.py
tests/integration/test_seldon_servers.py

Refactor integration tests due to issue #218. 
This is a workaround for the issue. At the same time, it is not needed to revert those back since up until now, integration tests were applying `seldondeployments` to the namespace created by Juju. In production, this would be `kubeflow` and we would never apply something there.

tests(integration): Apply seldondeployments in namespace `default`

---

config.yaml
src/charm.py
src/prometheus_alert_rules/unit_unavailable.rule
tests/integration/test_charm.py
tests/unit/test_operator.py

fix: correctly configure one scrape job to avoid firig alerts
The metrics endpoint configuration had two scrape jobs, one for the
regular metrics endpoint, and a second one based on a dynamic list of 
targets. The latter was causing the prometheus scraper to try and scrape
metrics from *:80/metrics, which is not a valid endpoint. This was
causing the UnitsUnavailable alert to fire constantly because that job
was reporting back that the endpoint was not available.
This new job was introduced by canonical/seldon-core-operator#94
with no apparent justification. Because the seldon charm has changed
since that PR, and the endpoint it is configuring is not valid, this
commit will remove the extra job.
This commit also refactors the MetricsEndpointProvider instantiation and
removes the …

fix: correct metrics path for MetricsEndpointProvider

---

.github/workflows/integrate.yaml

ci: Decrease root-reserve-mb to fit the new runner storage
addresses https://github.com/canonical/bundle-kubeflow/issues/813

ci: Decrease root-reserve-mb to fit the new runner storage (#238)

---

config.yaml
src/charm.py
src/prometheus_alert_rules/unit_unavailable.rule
tests/integration/test_charm.py
tests/unit/test_operator.py

* fix: correctly configure one scrape job to avoid firig alerts
The metrics endpoint configuration had two scrape jobs, one for the regular metrics endpoint, and a second one based on a dynamic list of targets. The latter was causing the prometheus scraper to try and scrape metrics from *:80/metrics, which is not a valid endpoint. This was causing the UnitsUnavailable alert to fire constantly because that job was reporting back that the endpoint was not available. This new job was introduced by canonical/seldon-core-operator#94 with no apparent justification. Because the seldon charm has changed since that PR, and the endpoint it is configuring is not valid, this commit will remove the extra job.
This commit also refactors the MetricsEndpointProvider instantiation and removes the …

fix: correct metrics path for MetricsEndpointProvider (#236)

---

tests/integration/test_charm.py

Adding a retry for checking the state of an alert will allow time to prometheus-k8s to scrape the necessary metrics for a unit, without it we may run into a race condition where the assertion of the metric is run before prometheus is even able to scrape. This commit adds a retry logic to avoid this.
Fixes #244 
TODO:

tests: add a retry when asserting the up metric

---

tests/integration/test_charm.py

* tests: add a retry when asserting the up metric
Adding a retry for checking the state of an alert will allow time to prometheus-k8s to scrape the necessary metrics for a unit, without it we may run into a race condition where the assertion of the metric is run before prometheus is even able to scrape. This commit adds a retry logic to avoid this.
Fixes #244

tests: add a retry when asserting the up metric (#243)

---

src/grafana_dashboards/seldon-core.json.tmpl

Backport the following:
* Fix grafana dashboard by removing `uid` from the `datasource` fields.
* Add tags `ckf` and `seldon` to dashboard.
Part of canonical/bundle-kubeflow#856
Refs canonical/bundle-kubeflow#834

backport(fix): Grafana dashboard shows data from #246

---

tests/integration/test_charm.py

Pins dependencies in the integration tests to their corresponding channels for this release.
Ref: https://github.com/canonical/bundle-kubeflow/issues/866

pin integration test dependencies for `track/1.17`

---

lib/charms/grafana_k8s/v0/grafana_dashboard.py
lib/charms/observability_libs/v0/metrics_endpoint_discovery.py
lib/charms/observability_libs/v1/kubernetes_service_patch.py
lib/charms/prometheus_k8s/v0/prometheus_scrape.py
requirements-unit.txt
requirements.in
requirements.txt

Ref canonical/bundle-kubeflow#880
Ref canonical/bundle-kubeflow#849

chore: Bump o11y libs and remove juju topology

---

lib/charms/loki_k8s/v1/loki_push_api.py
metadata.yaml
requirements-integration.in
requirements-integration.txt
requirements-unit.txt
requirements.txt
src/charm.py
tests/integration/test_charm.py
tests/unit/test_operator.py

Use LogForwarder from loki_push_api library to forwards all logs from workload container to Loki. This requires to use ops 2.9 or newer, so it was needed to be updated.
fixes: #253
How I tested it:
```bash
$ tox -e integration -- --keep-models
$ juju switch test-charm-3uzf
u1-k8s:admin/test-charm-aosq -> u1-k8s:admin/test-charm-3uzf
$ charmcraft pack
Created 'seldon-core_ubuntu-20.04-amd64.charm'.                                                 
Charms packed:
seldon-core_ubuntu-20.04-amd64.charm
$ juju deploy ./seldon-core_ubuntu-20.04-amd64.charm --resource oci-image=charmedkubeflow/seldon-core-operator:1.17.1-c95840c
Located local charm "seldon-core", revision 0
Deploying "seldon-core" from local charm "seldon-core", revision 0 on ubuntu@20.04/stable
$ juju integrate …
```

Add logging relation to seldon-core

---

.github/workflows/publish.yaml

Use charmcraft from latest/candidate in upload-charm in order to unify the channel used during integration tests and publishing.
Ref canonical/bundle-kubeflow#993

ci(upload-charm): use charmcraft from latest/candidate in track/1.17
